# 实验11（机器学习概述）作业题目

# 一. 概念题部分

# 二. 操作题部分

### 1. 数据归一化和正则化

In [41]:
import pandas as pd
import numpy as np

（1）创建表示5×5的随机矩阵的DataFrame对象，行索引和列索引都为0-4，元素取值在1-50。

In [42]:
ar  = np.random.uniform(1,51,25).reshape(5,5) #
frame = pd.DataFrame(ar)  #
frame

0          1          2          3          4
0  48.153469  32.979718  38.320435  22.182117   9.717035
1  11.121046  46.701263   1.412585   1.823877   7.976620
2   2.766875  25.759154  42.073755  42.881403  23.921329
3  20.917727  48.620580  26.422434   7.093828   6.951186
4  14.764109  35.349115  42.844038  41.023686  15.380562

（2）从sklearn包的preprocessing模块中导入用于归一化和正则化的类

In [43]:
from sklearn.preprocessing import MinMaxScaler # 导入库用于数据归一化
from sklearn.preprocessing import Normalizer   # 导入库用于数据正则化

（3）对前面生成的DataFrame数据进行归一化

In [44]:
# 转换器实例化
minmax_scaler = MinMaxScaler()  #
# 数据归一化
minmax_result = minmax_scaler.fit_transform(frame)  #
print("数据归一化：\n", minmax_result)

数据归一化：
 [[1.         0.31584048 0.89081716 0.49584672 0.1629832 ]
 [0.18406694 0.91604561 0.         0.         0.06042572]
 [0.         0.         0.98140824 1.         1.        ]
 [0.3999166  1.         0.60364401 0.12835529 0.        ]
 [0.26433432 0.4194822  1.         0.95475331 0.49671802]]


（4）对前面生成的DataFrame数据进行正则化

In [45]:
# 转换器实例化
normalizer_scaler = Normalizer() #
# 数据正则化
normalizer_result = normalizer_scaler.fit_transform(frame)  #
print("数据正则化：\n", normalizer_result)

数据正则化：
 [[0.65159528 0.44626958 0.51853822 0.30016036 0.13148739]
 [0.22826471 0.9585654  0.02899397 0.03743594 0.16372387]
 [0.03972004 0.36978707 0.6039923  0.61558654 0.34340407]
 [0.34871121 0.81053456 0.440478   0.11825842 0.1158805 ]
 [0.20429681 0.48913966 0.59284987 0.56766094 0.21282691]]


### 2. 训练集（train set）和测试集（test set）的划分

（1）从sklearn包的model_selection模块中导入用于划分训练集和测试集的类

In [46]:
from sklearn.model_selection import train_test_split   #

（2）设置字符串样本

In [47]:
s = "机器学习的研究涉及概率论统计学逼近论凸分析算法复杂度理论多门学科是人工智能的核心"

（3）设置特征集和标签集

In [48]:
X, y = list(s), range(40)

（4）将测试集和训练集的划分比例为2：8，设定随机数的编号为8，保证在重复试验中可得到相同的切分结果。

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=8)  #
print("测试集:", X_test)

测试集: ['智', '心', '学', '人', '近', '度', '杂', '机']


### 3.评价指标的计算

In [50]:
from sklearn import metrics
#导入标签二值化处理模块preprocessing.LabelBinarizer类
from sklearn import preprocessing  #

In [51]:
#生成LabelBinarizer类的对象
lb = preprocessing.LabelBinarizer()  #

In [52]:
#真值和预测值
y_true = ['男', '女', '男', '男', '男', '女', '女', '女','男', '女']    #真值
y_pred = ['男', '男', '男', '男', '女', '男', '女', '女', '男', '女']   #预测值

In [53]:
#手工计算混淆矩阵（假设要判断的是“是否是男”）
TP=4          #预测正确，预测类别为“男”的样本数
FP=1          #预测错误，预测类别为“男”的样本数
FN=2          #预测错误，预测类别为“女”的样本数
TN=3         #预测正确，预测类别为“女”的样本数
matrix=[[4,2],[1,3]]   #混淆矩阵[[TP,FN],[FP,TN]] 

In [54]:
# 计算混淆矩阵
print('Confusion Matrix：')
print(metrics.confusion_matrix(y_true, y_pred, labels=['男', '女']))   ###

Confusion Matrix：
[[4 1]
 [2 3]]


In [55]:
#手工计算分类的4个指标
#手工计算时请给出中间步骤
ACC=(4+3)/(4+1+2+3)     #准确率（Accuracy）=(TP+TN)/(TP+TN+FP+FN)
P = 4/(4+1)      #精确率（Precision）=TP/(TP+FP)
R = 4/(4+2)       #召回率（Recall）=TP/(TP+FN)
F1 =(2*(4/5)*(4/6))/((4/5)+(4/6))       #F1分数（F1 Score）=2*P*R/(P+R)

In [56]:
# 利用LabelBinarizer对象将标签二值化，再分别计算精确率、召回率、F1分数和准确率
y_true_binarized = lb.fit_transform(y_true)
y_pred_binarized = lb.fit_transform(y_pred)
print('准确率ACC： %s' % metrics.precision_score(y_true_binarized, y_pred_binarized))
print('精确率P： %s' % metrics.recall_score(y_true_binarized, y_pred_binarized))
print('召回率R： %s' % metrics.f1_score(y_true_binarized, y_pred_binarized))
print('F1分数：%s' % metrics.accuracy_score(y_true_binarized, y_pred_binarized))

准确率ACC： 0.6666666666666666
精确率P： 0.8
召回率R： 0.7272727272727272
F1分数：0.7


In [57]:
# 利用classification_report()函数实现对精确率、召回率、F1分数和准确率的计算
print('Classification Report：')
print(metrics.classification_report(y_true,y_pred)) #

Classification Report：
              precision    recall  f1-score   support

           女       0.75      0.60      0.67         5
           男       0.67      0.80      0.73         5

    accuracy                           0.70        10
   macro avg       0.71      0.70      0.70        10
weighted avg       0.71      0.70      0.70        10



### 4.综合应用

小明和小张想对某股票的价格进行回归分析，已经获得了某股票在一段时间内的收盘价，两人分别用不同次数的多项式对收盘价进行拟合（小明用3次多项式，小张用5次多项式），请根据回归评价指标MAE、MSE等判断两人中谁的方法更好。

（1）数据准备

In [58]:
import numpy as np
#polyfit()函数可以对一组数据使用多项式函数进行拟合，找到和这组数据最接近的多项式的系数

#第一步：
x = np.arange(1,28)

#第二步：某股票在28个交易日的收盘价
y = [17.89,18.47,19.04,18.61,18.25,18.23,17,18.22,18.19,18.33,18.42,18.58,18.46,
     17.59,17.6,17.75,16.98,16.67,16.92,16.77,16.85,16.74,16.71,16.34,16.11,15.81,17.57]
y = np.array(y)

In [59]:
#第三步：将目标函数的数组传递给polyfit()进行拟合，
#第三个参数arg为多项式函数的最高阶数。
#polyfit()所得到的多项式和目标函数在给定的1000个点之间的误差最小，
#polyfit()返回多项式的系数数组。
f3 = np.polyfit(x, y, 3)     #小明
f5 = np.polyfit(x, y, 5)     #小张

#根据多项式系数得到多项式函数
pf3 = np.poly1d(f3)
print(pf3)
pf5 = np.poly1d(f5)
print(pf5)
f3

           3           2
0.0005249 x - 0.02405 x + 0.2183 x + 17.9
           5             4           3           2
5.633e-06 x - 0.0003281 x + 0.00673 x - 0.06363 x + 0.241 x + 18.07


array([ 5.24887841e-04, -2.40535837e-02,  2.18294544e-01,  1.78991823e+01])

In [60]:
#小明的拟合结果
y1=pf3(x)
y1

array([18.09394818, 18.24375619, 18.35175569, 18.421096  , 18.45492645,
       18.45639636, 18.42865507, 18.37485191, 18.29813619, 18.20165725,
       18.08856441, 17.962007  , 17.82513435, 17.68109579, 17.53304063,
       17.38411821, 17.23747786, 17.0962689 , 16.96364066, 16.84274247,
       16.73672365, 16.64873353, 16.58192143, 16.5394367 , 16.52442864,
       16.54004659, 16.58943988])

In [61]:
#小张的拟合结果
y2=pf5(x)
y2

array([18.25670251, 18.3491801 , 18.37976899, 18.37135822, 18.34098939,
       18.30053263, 18.25736263, 18.21503453, 18.17395995, 18.13208294,
       18.08555591, 18.02941569, 17.95825941, 17.86692052, 17.75114474,
       17.60826603, 17.4378826 , 17.24253279, 17.02837113, 16.80584428,
       16.59036697, 16.40299802, 16.27111625, 16.22909651, 16.31898562,
       16.59117833, 17.10509331])

（2）计算回归评价指标

In [62]:
from sklearn import metrics    #

In [63]:
# 计算MAE
print('MAE：')
print('小明的MAE： %s' % metrics.mean_absolute_error(y,y1))  #
print('小张的MAE： %s' % metrics.mean_absolute_error(y,y2))  #

MAE：
小明的MAE： 0.33792976098212335
小张的MAE： 0.3243294190297237


In [64]:
# 计算MSE
print('MSE：')
print('小明的MSE： %s' % metrics.mean_squared_error(y,y1)) #
print('小张的MSE： %s' % metrics.mean_squared_error(y,y2)) #

MSE：
小明的MSE： 0.21588223051297073
小张的MSE： 0.18031033294858906


In [65]:
# 计算决定系数
print('R2：')
print('小明的R2： %s' % metrics.r2_score(y,y1)) #
print('小张的R2：%s' % metrics.r2_score(y,y2)) #

R2：
小明的R2： 0.7119747548627833
小张的R2：0.7594339852572062


（3）结论