# numpy和pandas综合练习（作业）

第一部分：Numpy

In [1]:
import numpy as np
Z = np._________________  #创建一个由10到20之间的随机整数组成的5*5二维NumPy数组Z
print("矩阵 Z=\n", Z)
Zmin = Z.________  #取最小值
Zmax = Z.________  #取最大值
Z = (Z - Zmin) / (Zmax - Zmin)
print("归一化后的Z：\n", Z)

矩阵 Z=
 [[18 11 15 13 10]
 [11 15 17 11 11]
 [15 17 11 13 10]
 [16 15 13 17 19]
 [18 15 13 10 19]]
归一化后的Z：
 [[0.88888889 0.11111111 0.55555556 0.33333333 0.        ]
 [0.11111111 0.55555556 0.77777778 0.11111111 0.11111111]
 [0.55555556 0.77777778 0.11111111 0.33333333 0.        ]
 [0.66666667 0.55555556 0.33333333 0.77777778 1.        ]
 [0.88888889 0.55555556 0.33333333 0.         1.        ]]


In [2]:
import numpy as np
arr = np._________________.reshape(4, 4)    #创建一个由1~16的整数组成的一维NumPy数组对象,再变换为4*4二维数组对象arr
print(arr)
num_1 = arr[_______]  #获取arr数组中第二行（行位置索引为1）第一列元素（列位置索引为0）
num_2 = arr[_______]  ##获取arr数组中第三行第二列元素
print(num_1, num_2)
arr2 = arr[______________]  #获取arr数组中除了第一列和第一行以外的数据；
print(arr2)
mask = (_______________)  #使用布尔运算方式找出arr数组中为奇数的数据
arr[_________] = 0  #将arr数组中为奇数的数据都置为零
print(arr)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
5.0 10.0
[[ 6.  7.  8.]
 [10. 11. 12.]
 [14. 15. 16.]]
[[ 0.  2.  0.  4.]
 [ 0.  6.  0.  8.]
 [ 0. 10.  0. 12.]
 [ 0. 14.  0. 16.]]


In [3]:
import numpy as np
arr = np.__________________  #创建20到40之间均匀分布的4*5二维NumPy数组对象
print(arr)
row_mean = arr.______(axis=____)  #计算数组中每行的平均值
col_max = arr._______(axis=____)  #计算数组中每列的最大值
index_max = arr.__________  #返回数组中最小值的索引
print(row_mean)
print(col_max)
print(index_max)

[[37.10107009 35.44080985 37.12194036 28.25104284 28.95777257]
 [39.11298622 23.82313286 21.39324598 35.51087423 21.7627372 ]
 [34.53068559 29.30399945 29.2085531  29.52306091 32.21076152]
 [31.94231065 27.51663931 26.21442091 39.08212609 23.27088909]]
[33.37452714 28.3205953  30.95541211 29.60527721]
[39.11298622 35.44080985 37.12194036 39.08212609 32.21076152]
7


第二部分：Pandas

In [4]:
import pandas as pd
import numpy as np
data = np.__________________ #创建一个存储了21~30的整数的一维数组；
index = np.arange(1, 11, 1)
num = pd.Series(____________________) #创建一个存储了21~30的整数的Series对象，索引值为1~10；
print(num)
num[_______________] = 0   #将其中小于等于25的元素赋值为0
print(num)

1     21
2     22
3     23
4     24
5     25
6     26
7     27
8     28
9     29
10    30
dtype: int32
1      0
2      0
3      0
4      0
5      0
6     26
7     27
8     28
9     29
10    30
dtype: int32


In [5]:
import pandas as pd
import numpy as np
month = ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月']
money = np._______________________________ #生成尺寸为12*2的二维随机整数数组,元素值为5000~10000的随机数
account = pd.DataFrame(________, ___________, columns=['收入', '支出'])  # 创建DataFrame对象
print(account)
account_new = ________________ #取出‘支出’列作为新的DataFrame对象
print(account_new)
# 从DataFrame对象写入数据到CSV文件
account_new.__________(r'______\account.csv')  #DataFrame对象写入到CSV文件

       收入    支出
1月   6866  7558
2月   8761  9046
3月   6143  5772
4月   7445  8184
5月   8003  5632
6月   7232  6644
7月   8547  9745
8月   7018  7408
9月   5274  7913
10月  6744  5964
11月  5644  5931
12月  6302  6196
1月     7558
2月     9046
3月     5772
4月     8184
5月     5632
6月     6644
7月     9745
8月     7408
9月     7913
10月    5964
11月    5931
12月    6196
Name: 支出, dtype: int32


In [6]:
import pandas as pd
# 从CSV文件读取数据到DataFrame对象
boston = pd._______________(r'__________\Boston_pandas.csv')  #
print(boston)
# 删除行索引值为1、2和3的元素
boston = boston.______([1, 2, 3], axis=____)  #
print(boston)
# 修改 'MEDV' 列的数据内容为15
boston[________] = 15   #
print(boston)

      CRIM    NOX     RM   AGE  LSTAT  MEDV
0  0.08829  0.524  6.012  66.6  12.43  22.9
1  0.14455    NaN  6.172  96.1  19.15  27.1
2  0.21124  0.524    NaN   NaN  29.93  16.5
3  0.17004    NaN  6.004  85.9  17.10  18.9
4  0.22489  0.524  6.377  94.3  20.45  15.0
5  0.22489  0.524  6.377  94.3  20.45  15.0
      CRIM    NOX     RM   AGE  LSTAT  MEDV
0  0.08829  0.524  6.012  66.6  12.43  22.9
4  0.22489  0.524  6.377  94.3  20.45  15.0
5  0.22489  0.524  6.377  94.3  20.45  15.0
      CRIM    NOX     RM   AGE  LSTAT  MEDV
0  0.08829  0.524  6.012  66.6  12.43    15
4  0.22489  0.524  6.377  94.3  20.45    15
5  0.22489  0.524  6.377  94.3  20.45    15
